#pragma once

// https://tools.ietf.org/html/rfc1928

#define SOCKS_VERSION 5
#define SOCKS_AUTH_NONE 0
#define SOCKS_AUTH_NO_ACCEPTABLE 0xff
#define SOCKS_CMD_CONNECT 1
#define SOCKS_ATYPE_IPV4 1
#define SOCKS_ATYPE_DOMAIN 3
#define SOCKS_ATYPE_IPV6 4
#define SOCKS_REPLY_SUCCESS 0
#define SOCKS_REPLY_SERVERROR 1
#define SOCKS_REPLY_NETUNREACH 3
#define SOCKS_REPLY_HOSTUNREACH 4
#define SOCKS_REPLY_CONNREFUSED 5
#define SOCKS_REPLY_CMDNOTSUPP 7
#define SOCKS_REPLY_ATYPENOTSUPP 8
